//

// Premier morceau  Ndef


// Intro


// 2e morceau que des kicks

// 3e morceau que des snares

// 4e morceau que des hihats


// 5e morceau que des cowbells

// 6e morceau que des samples waveshaping granular convolution

// 7e morceau que des cuspn

// 8e morceau que des 9 ou des 7 pas de 8

// 9e morceau que du feedback


// 10e morceau que en dessous 108

// 11e morceau vocals traitement

// 12e morceau field recording